# SPDX-FileCopyrightText: 2021 Michael Schroeder
#
# SPDX-License-Identifier: MIT

name: Run pre-commit

on: [pull_request, push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3
    - name: Versions
      run: |
        python3 --version
    - name: Checkout Current Repo
      uses: actions/checkout@v3
    - name: Pip install requirements
      run: |
        pip install --force-reinstall -r requirements.txt
    - name: Pip install pre-commit
      run: |
        pip install pre-commit
    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files
